# 示例配置文件
# 复制此文件并根据需要修改

paths:
  # 输入视频/音频文件路径（请修改为实际路径）
  input_file: "input/my_video.mp4"
  
  # 输出wav文件路径
  output_wav: "output/my_audio.wav"
  
  # 输出ASS字幕文件路径
  output_ass: "output/my_subtitle.ass"

audio:
  # 采样率（Hz），Silero VAD要求16000Hz
  sample_rate: 16000
  
  # FFmpeg路径（如果在PATH中可直接使用"ffmpeg"）
  ffmpeg_path: "ffmpeg"

vad:
  # 使用ONNX模型（推荐）
  use_onnx: true
  
  # 语音检测阈值（0-1），值越大越严格，默认0.5
  # 如果检测到的语音太少，可以降低此值（如0.3）
  # 如果检测到太多噪音，可以提高此值（如0.7）
  threshold: 0.5
  
  # 最小语音持续时间（毫秒），短于此时间的语音会被过滤
  min_speech_duration_ms: 250
  
  # 最大语音持续时间（秒），超过此时间会自动分割
  max_speech_duration_s: .inf
  
  # 最小静音持续时间（毫秒）
  min_silence_duration_ms: 100
  
  # 语音片段前后填充时间（毫秒）
  speech_pad_ms: 30

subtitle:
  # 字幕标题
  title: "我的字幕"
  
  # 视频分辨率（用于字幕定位）
  resolution:
    width: 1920
    height: 1080
  
  # 时间戳预处理配置
  # 最小间隔（秒）：间隔小于此值时，调整时间戳使其相连
  # 默认0.5秒，避免过小的间隔导致字幕闪烁
  merge_min_gap: 0.5
  
  # 字幕样式
  style:
    name: "Default"
    fontname: "Microsoft YaHei"
    fontsize: 56
    primary_colour: "&H00FFFFFF"
    secondary_colour: "&H000000FF"
    outline_colour: "&H00000000"
    back_colour: "&H80000000"
    bold: 0
    italic: 0
    underline: 0
    strikeout: 0
    scale_x: 100
    scale_y: 100
    spacing: 0
    angle: 0
    border_style: 1
    outline: 2
    shadow: 3
    alignment: 2
    margin_l: 10
    margin_r: 10
    margin_v: 25
    encoding: 1

